name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: ko-build/setup-ko@v0.6
      - run: |
          tag=$(echo ${{ github.ref }} | cut -c11-)
          ko build -t latest,${tag} -B
