name: Publish

on:
  tags:
    - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: |
          tag=$(echo ${{ github.ref }} | cut -c11-)
          ko build -t ${tag}